### ISSUE TITLE
I have got so many the following exception .

### ISSUE THREAD

**Issue by STerOTto** [johntostring/millimall#3]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableRedisKeyspaceNotificationsInitializer' defined in org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration: Invocation of init method failed; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
2017-04-05T13:35:14.121352300Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2017-04-05T13:35:14.121354800Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2017-04-05T13:35:14.121356900Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2017-04-05T13:35:14.121358900Z 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2017-04-05T13:35:14.121360900Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2017-04-05T13:35:14.121363000Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2017-04-05T13:35:14.121365000Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2017-04-05T13:35:14.121367000Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2017-04-05T13:35:14.121369700Z 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2017-04-05T13:35:14.121371900Z 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2017-04-05T13:35:14.121373900Z 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
2017-04-05T13:35:14.121375900Z 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
2017-04-05T13:35:14.121377800Z 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
2017-04-05T13:35:14.121379800Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
2017-04-05T13:35:14.121381700Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
2017-04-05T13:35:14.121383600Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
2017-04-05T13:35:14.121385500Z 	at com.millinch.mall.oauth2.OAuth2ServerApplication.main(OAuth2ServerApplication.java:71) [classes!/:na]
2017-04-05T13:35:14.121387300Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
2017-04-05T13:35:14.121394200Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
2017-04-05T13:35:14.121396500Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
2017-04-05T13:35:14.121398400Z 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
2017-04-05T13:35:14.121400200Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app.jar:na]
2017-04-05T13:35:14.121402100Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app.jar:na]
2017-04-05T13:35:14.121404000Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app.jar:na]
2017-04-05T13:35:14.121405800Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app.jar:na]
2017-04-05T13:35:14.121408000Z Caused by: org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
2017-04-05T13:35:14.121410100Z 	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:204) ~[spring-data-redis-1.8.0.RELEASE.jar!/:na]
2017-04-05T13:35:14.121412100Z 	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:348) ~[spring-data-redis-1.8.0.RELEASE.jar!/:na]
2017-04-05T13:35:14.121414100Z 	at org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration$EnableRedisKeyspaceNotificationsInitializer.afterPropertiesSet(RedisHttpSessionConfiguration.java:249) ~[spring-session-1.3.0.RELEASE.jar!/:na]
2017-04-05T13:35:14.121416200Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2017-04-05T13:35:14.121418200Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
2017-04-05T13:35:14.121420300Z 	... 24 common frames omitted
2017-04-05T13:35:14.121422000Z Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
2017-04-05T13:35:14.121423900Z 	at redis.clients.util.Pool.getResource(Pool.java:53) ~[jedis-2.9.0.jar!/:na]
2017-04-05T13:35:14.121425800Z 	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226) ~[jedis-2.9.0.jar!/:na]
2017-04-05T13:35:14.121427700Z 	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:16) ~[jedis-2.9.0.jar!/:na]
2017-04-05T13:35:14.121429500Z 	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:194) ~[spring-data-redis-1.8.0.RELEASE.jar!/:na]
2017-04-05T13:35:14.121435100Z 	... 28 common frames omitted
2017-04-05T13:35:14.121437200Z Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.UnknownHostException: RedisServer
2017-04-05T13:35:14.121439000Z 	at redis.clients.jedis.Connection.connect(Connection.java:207) ~[jedis-2.9.0.jar!/:na]
2017-04-05T13:35:14.121442700Z 	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93) ~[jedis-2.9.0.jar!/:na]
2017-04-05T13:35:14.121445100Z 	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1767) ~[jedis-2.9.0.jar!/:na]
2017-04-05T13:35:14.121447100Z 	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:106) ~[jedis-2.9.0.jar!/:na]
2017-04-05T13:35:14.121450900Z 	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868) ~[commons-pool2-2.4.2.jar!/:2.4.2]
2017-04-05T13:35:14.121452900Z 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435) ~[commons-pool2-2.4.2.jar!/:2.4.2]
2017-04-05T13:35:14.121454800Z 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363) ~[commons-pool2-2.4.2.jar!/:2.4.2]
2017-04-05T13:35:14.121456700Z 	at redis.clients.util.Pool.getResource(Pool.java:49) ~[jedis-2.9.0.jar!/:na]
2017-04-05T13:35:14.121458600Z 	... 31 common frames omitted
2017-04-05T13:35:14.121460400Z Caused by: java.net.UnknownHostException: RedisServer
2017-04-05T13:35:14.121462200Z 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_121]
2017-04-05T13:35:14.121464000Z 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_121]
2017-04-05T13:35:14.121465900Z 	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_121]
2017-04-05T13:35:14.121467700Z 	at redis.clients.jedis.Connection.connect(Connection.java:184) ~[jedis-2.9.0.jar!/:na]
2017-04-05T13:35:14.121469600Z 	... 38 common frames omitted

**Comment by johntostring** [comment]
I am sorry that the project is being developed, the document will be perfect later. But it is still hard to start right now.

Obviously because Redis host configuration is not correct. If you use the docker to run Redis, you should expose a port, and then localhost can connect to Redis through this port. Through the name of the container is not accessible.(between the containers is possible)
